# Generated by Django 4.2.7 on 2023-11-20 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='comment_admin',
            field=models.TextField(blank=True, help_text='добавить комментарий при смене статуса на принят в работу', verbose_name='комментарий'),
        ),
        migrations.AddField(
            model_name='application',
            name='image_admin',
            field=models.ImageField(blank=True, help_text='добавить изображение при смене статуса на выполнено', upload_to='images_admin', verbose_name='изображение готового дизайна'),
        ),
    ]
